name: Frontend CI
on: 
  push:
    branches: [ main, development, feature/**,  enhance/**, refactor/**, bugfix/** ]
  pull_request:
    branches: [ development ]
jobs:
  build-lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2

      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install dependencies
        run: |
          if [ -d node_modules ]; then
            echo "Cache hit, skipping dependency step"
          else
            npm ci
          fi

      - name: build production project
        run: npm run build:prod
        if: always()
      - name: linting typesctipt
        run: npm run lint:ts
        if: always()
      - name: linting css
        run: npm run lint:scss
        if: always()
      - name: unit testing
        run: npm run test:unit
        if: always()
